server:
  port: 8090
spring:
  application:
    name: blog-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

zuul:
  retryable: true
  ignored-services:
    - listener-service # 忽略upload-service服务
  routes:
    user-service: /user/** # 这里是映射路径
    article-service: /article/**
    upload-service: /upload/**
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
